### ISSUE TITLE
Add a DMN Editor

### ISSUE THREAD

**Issue by Abbaskarara52** [duckflow/webapp#10]
DMN is a great way to model business decisions/rules - [wiki](https://en.wikipedia.org/wiki/Decision_Model_and_Notation) 

Modeler can be implemented using [bpmn-io plugin](https://github.com/bpmn-io/dmn-js) - more about this [here](https://bpmn.io/toolkit/dmn-js/)
and a link can be made from within the bpmn model using key of the decision table.

**Comment by DenysVuika** [comment]
Initial implementation is featured in the 0.12.0 milestone. Closing this ticket as done.
